Magento product sync
YetiForceCompany/YetiForceCRM pull request #10616
Opened 2019-06-03 20:49 UTC by adudekyeti

Magento product sync

2019-06-03 21:25 UTC, BlackDuckCoPilot commented
## Black Duck Security Report

Merging #10616 into developer will not change security risk.

[Click here to see full report](https://copilot.blackducksoftware.com/github/repos/YetiForceCompany/YetiForceCRM/pull-requests/10616)

2019-06-04 05:41 UTC, rskrzypczak requested changes

2019-06-04 05:41 UTC, rskrzypczak commented on app/Integrations/Magento/Config.php
> +	 * @return config
?

2019-06-04 05:41 UTC, rskrzypczak commented on app/Integrations/Magento/Config.php
> +		if (!(new Query())->from('i_#__magento_config')
move table name to const

2019-06-04 05:41 UTC, rskrzypczak commented on app/Integrations/Magento/Config.php
> +	public static function setStartScan(string $type): void
try to merge functions (setStartScan, setLastScanId)

2019-06-04 05:41 UTC, rskrzypczak commented on app/Integrations/Magento/Config.php
> +			'end_date' => self::getInstance()->get($type . '_end_scan_date') ?? false,
why you create so many self::getInstance() ?

2019-06-04 05:47 UTC, rskrzypczak commented on app/Integrations/Magento/Synchronizator/Record.php
> +	public function whichToUpdate(array $recordYF, array $recordMagento)
$recordYF, $recordMagento?

2019-06-04 05:47 UTC, rskrzypczak commented on app/Integrations/Magento/Synchronizator/Record.php
> +		$modifiedTimeYFStart = strtotime($recordYF['modifiedtime']) < strtotime($this->lastScan['start_date']);
for optimization

2019-06-04 05:47 UTC, rskrzypczak commented on app/Integrations/Magento/Synchronizator/Record.php
> +	public function getFormatedRecordsIds($ids, $formatTo = 'magento'): array
?

2019-06-04 05:54 UTC, rskrzypczak commented on app/Integrations/Magento/Synchronizator/Base.php
> +	 * @param bool $limit
?

2019-06-04 10:26 UTC, TomaszQr requested changes

2019-06-04 10:26 UTC, TomaszQr commented on app/Integrations/Magento/Config.php
> +		static::updateData();
$this->set($data['name'], data['value']);

2019-06-04 10:26 UTC, TomaszQr commented on app/Integrations/Magento/Config.php
> +	public static function updateData(): void
to remove

2019-06-04 10:26 UTC, TomaszQr commented on app/Integrations/Magento/Synchronizator/Product.php
> +		$query = $queryGenerator->createQuery();
fields ?

2019-08-12 08:45 UTC, TomaszQr approved these changes

2020-03-23 07:23 UTC, mariuszkrzaczkowski commented on app/Fields/File.php
> +	public static function saveImageFromUrl($url, $moduleName): array
?

2020-03-23 07:23 UTC, mariuszkrzaczkowski commented on app/Integrations/Magento/Synchronizator/Base.php
> +			'currency' => \App\Config::component('Magento', 'currencyId'),
?

2020-03-23 07:23 UTC, mariuszkrzaczkowski commented on app/Integrations/Magento/Synchronizator/Base.php
> +			'name' => \App\Config::component('Magento', 'shippingServiceId'),
?

2020-03-23 07:23 UTC, mariuszkrzaczkowski commented on app/Integrations/Magento/Synchronizator/Base.php
> +	public function getProductSkuMapCrm(): void
?

2020-03-23 07:23 UTC, mariuszkrzaczkowski commented on app/Integrations/Magento/Synchronizator/Integrators/Customer.php
> +	public static $groups = [];
?

2020-03-23 07:23 UTC, mariuszkrzaczkowski commented on app/Integrations/Magento/Synchronizator/Maps/Customer.php
> +
?

2020-03-23 07:23 UTC, mariuszkrzaczkowski commented on app/Integrations/Magento/Synchronizator/Maps/Customer.php
> +
?

2020-03-23 07:23 UTC, mariuszkrzaczkowski commented on config/Components/ConfigTemplates.php
> +			'validation' => function () {
?

2020-03-23 07:23 UTC, mariuszkrzaczkowski commented on modules/Settings/Magento/views/Index.php
> +			"modules.Settings.{$request->getModule()}.resources.Edit",
?

2020-03-23 07:24 UTC, merged

2020-03-24 13:31 UTC, mariuszkrzaczkowski commented on app/Integrations/Magento/Synchronizator/Maps/Base.php
> +	public function getDataCrm(bool $onEdit = false): array
?