Improved adding relation on OSSMailScanner
YetiForceCompany/YetiForceCRM pull request #11530
Opened 2019-09-17 11:06 UTC by adudekyeti

Improved adding relation on OSSMailScanner

2019-11-05 05:28 UTC, rskrzypczak requested changes

2019-11-05 05:28 UTC, rskrzypczak commented on modules/OSSMailScanner/models/PrefixScannerAction.php
> +					if ($this->prefix) {
remove this condition (duplicate)

2019-11-05 05:28 UTC, rskrzypczak commented on modules/OSSMailScanner/models/PrefixScannerAction.php
> +				if (\App\Record::getType($crmId) === $this->moduleName) {
remove loop
add join to query and add condition [setype =>$this->moduleName, ['<>',deleted,1]]

2019-11-05 05:28 UTC, rskrzypczak commented on modules/OSSMailScanner/models/PrefixScannerAction.php
> +				\App\Cache::save('getRecordByPrefix', $prefixes, $crmId, \App\Cache::LONG);
where do you clear this variable?

2019-11-05 05:28 UTC, rskrzypczak commented on modules/OSSMailScanner/models/PrefixScannerAction.php
> +		\App\RecordStatus::getStates($this->moduleName, \App\RecordStatus::RECORD_STATE_OPEN), 'e', false);
What happens if the module does not support the status mechanism?

2019-11-05 05:28 UTC, rskrzypczak commented on modules/OSSMailScanner/scanneractions/CreatedHelpDesk.php
> +		if(!$contactId && !$parentId && \App\Process::$requestMode !== 'WebUI' && !\App\Config::module('OSSMailScanner', 'CREATE_TICKET_WITHOUT_CONTACT')){
> \App\Process::$requestMode !== 'WebUI'

?

2020-10-30 06:25 UTC, mariuszkrzaczkowski requested changes

2020-10-30 06:25 UTC, mariuszkrzaczkowski commented on modules/OSSMailScanner/ConfigTemplate.php
> +		'default' => true,
```suggestion
		'default' => false,
```

2020-10-30 06:25 UTC, mariuszkrzaczkowski commented on modules/OSSMailScanner/scanneractions/CreatedHelpDesk.php
> +		if(!$contactId && !$parentId && \App\Process::$requestMode !== 'WebUI' && !\App\Config::module('OSSMailScanner', 'CREATE_TICKET_WITHOUT_CONTACT')){
?

2020-10-30 11:39 UTC, adudekyeti commented
Duplicate #13710

2020-10-30 11:39 UTC, closed without merging