Add user login history in reports
YetiForceCompany/YetiForceCRM pull request #12426
Opened 2020-01-17 11:26 UTC by adudekyeti

Add user login history in reports

2020-01-21 11:28 UTC, rskrzypczak requested changes

2020-01-21 11:28 UTC, rskrzypczak commented on app/TextParser/UserLoginHistory.php
> +			$html = '<table><tr><td>' . \App\Language::translate('LBL_IP', 'Other:Reports') . '</td><td>' . \App\Language::translate('LBL_DATE') . '</td><td>' . \App\Language::translate('LBL_AGENT', 'Other:Re
'Other:Reports' ?

2020-01-21 11:28 UTC, rskrzypczak commented on app/TextParser/UserLoginHistory.php
> +			foreach ($historyLogin as $data) {
$dataReader
while()

2020-01-21 11:28 UTC, rskrzypczak commented on modules/Users/models/Module.php
> +				'userid' => \App\User::getUserIdByName($userName) ?? false,
```suggestion
				'userid' => \App\User::getUserIdByName($userName),
```
and chenge in getUserIdByName(): ?int

2020-01-21 12:01 UTC, adudekyeti commented on app/TextParser/UserLoginHistory.php
> +			$html = '<table><tr><td>' . \App\Language::translate('LBL_IP', 'Other:Reports') . '</td><td>' . \App\Language::translate('LBL_DATE') . '</td><td>' . \App\Language::translate('LBL_AGENT', 'Other:Re
+ agent to browser

2020-01-21 12:04 UTC, adudekyeti commented on app/TextParser/UserLoginHistory.php
> +		return $existLoginHistory ? $html : \App\Language::translate('LBL_NO_RECORDS', 'Other.Reports');
?

2020-03-03 08:39 UTC, rskrzypczak requested changes

2020-03-03 08:39 UTC, rskrzypczak commented on app/User.php
>  		Cache::save(__METHOD__, $name, $userId, Cache::LONG);
?
Cache::save(__METHOD__, $name, $userId, Cache::LONG);
$userId !== false ? $userId : null;

2020-05-12 08:32 UTC, merged