Change tree view from select to modal on listview
YetiForceCompany/YetiForceCRM pull request #12805
Opened 2020-04-01 11:03 UTC by adudekyeti

![image](https://user-images.githubusercontent.com/39482453/78128592-79376f00-7416-11ea-91ce-69761eaa5099.png)
After click, show modal:

![image](https://user-images.githubusercontent.com/39482453/78128620-82c0d700-7416-11ea-91f0-1c2a7d23c45c.png)

2020-04-01 13:39 UTC, rskrzypczak requested changes

2020-04-01 13:39 UTC, rskrzypczak commented on modules/Vtiger/views/RecordsList.php
> +			'~layouts/resources/Fields.js',
?

2020-04-01 13:39 UTC, rskrzypczak commented on public_html/layouts/basic/modules/Vtiger/resources/ListSearch.js
> +			vtigerEditInstance.registerTreeAutoCompleteFields(this.container);
move registerTreeAutoCompleteFields, registerClearTreeSelectionEvent to App.Fields.Tree

2020-04-01 13:39 UTC, rskrzypczak commented on modules/Vtiger/uitypes/Tree.php
> +		if (false === strpos($value, ',')) {
?

2020-04-01 13:39 UTC, rskrzypczak commented on layouts/basic/modules/Vtiger/Modals/RecordsList.tpl
> +									<input name="searchInSubcategories" value="1" type="checkbox" class="searchInSubcategories mr-1" id="searchInSubcategories{$LISTVIEW_HEADER_NAME}" title="{\App\Language::translate('LBL_SEARC
```suggestion
								<div class="d-flex align-items-center">
									<input name="searchInSubcategories" value="1" type="checkbox" class="searchInSubcategories mr-1" id="searchInSubcategories{\App\Layout::getUniqueId()}" title="{\App\Language::translate('LBL_SEARCH_IN_SUBCATEGORIES',$MODULE_NAME)}" data-columnname="{$LISTVIEW_HEADER->getColumnName()}" {if !empty($SEARCH_DETAILS[$LISTVIEW_HEADER->getName()]['specialOption'])} checked {/if}>
```

2020-04-08 10:17 UTC, adudekyeti commented on modules/Vtiger/uitypes/Tree.php
> +		if (false === strpos($value, ',')) {
?

2020-05-13 10:05 UTC, merged