Fixed #12787
YetiForceCompany/YetiForceCRM pull request #12814
Opened 2020-04-03 09:07 UTC by areksolek

![projectWidget](https://user-images.githubusercontent.com/25615135/78343441-21764080-759b-11ea-95d0-fe842815dc23.gif)

2020-04-07 06:58 UTC, rskrzypczak requested changes

2020-04-07 06:58 UTC, rskrzypczak commented on public_html/layouts/basic/modules/Vtiger/resources/Detail.js
> +				.find('.js-switch, .js-detail-widget-header, .js-filter_field')
revert

2020-04-07 06:58 UTC, rskrzypczak commented on layouts/basic/modules/Vtiger/Detail/Widget/Basic.tpl
> +				{assign var=RELATED_MODULE_MODEL value=Vtiger_Module_Model::getInstance($RELATED_MODULE_NAME)}
duplicate

2020-04-08 06:47 UTC, areksolek commented on layouts/basic/modules/Vtiger/Detail/Widget/Basic.tpl
> +				{assign var=RELATED_MODULE_MODEL value=Vtiger_Module_Model::getInstance($RELATED_MODULE_NAME)}
the duplicate has been removed

2020-04-20 08:54 UTC, mariuszkrzaczkowski approved these changes

2020-04-20 09:00 UTC, merged