Added configuration proxy
YetiForceCompany/YetiForceCRM pull request #13161
Opened 2020-06-09 18:50 UTC by areksolek

Added configuration proxy

2020-06-10 04:47 UTC, rskrzypczak commented on languages/en-US/Settings/_Base.json
> +    "LBL_PROXY_PASSWORD": "Password",
move to languages/en-US/Settings/Proxy.json

2020-06-10 04:47 UTC, rskrzypczak commented on layouts/basic/modules/Settings/Proxy/ConfigProxyDetail.tpl
> +
`<!-- tpl ..`

2020-06-10 04:47 UTC, rskrzypczak commented on layouts/basic/modules/Settings/Proxy/ConfigProxyEdit.tpl
> +-->*}
wrong license and rename file and use `<!-- tpl..`

2020-06-10 04:47 UTC, rskrzypczak commented on modules/Settings/Proxy/actions/ConfigProxySaveAjax.php
> + * ********************************************************************************** */
wrong license and rename file

2020-06-12 09:35 UTC, rskrzypczak commented on layouts/basic/modules/Settings/Proxy/ConfigProxyEdit.tpl
> +	<div class="tpl-Settings-Vtiger-ConfigProxyEdit">
```suggestion
	<div class="tpl-Settings-Proxy-Edit">
```

2020-06-12 09:35 UTC, rskrzypczak commented on layouts/basic/modules/Settings/Proxy/ConfigProxyEdit.tpl
> +							<td width="30%" class="{$WIDTHTYPE} textAlignRight">
deprecated: textAlignRight

2020-06-12 09:35 UTC, rskrzypczak commented on modules/Settings/Proxy/actions/ConfigProxySaveAjax.php
> +class Settings_Proxy_ConfigProxySaveAjax_Action extends Settings_Vtiger_Basic_Action
```suggestion
class Settings_Proxy_SaveAjax_Action extends Settings_Vtiger_Basic_Action
```
and add @package

2020-06-12 09:35 UTC, rskrzypczak commented on modules/Settings/Proxy/models/ConfigModule.php
> +class Settings_Proxy_ConfigModule_Model extends Settings_Vtiger_Module_Model
```suggestion
class Settings_Proxy_Module_Model extends Settings_Vtiger_Module_Model
```

2020-06-15 04:53 UTC, rskrzypczak commented on modules/Settings/Proxy/views/ConfigProxyEdit.php
> +	public function process(App\Request $request)
dec

2020-06-15 04:53 UTC, rskrzypczak commented on modules/Settings/Proxy/views/ConfigProxyEdit.php
> +			"modules.Settings.Proxy.resources.ConfigEditor",
?

2020-06-15 04:53 UTC, rskrzypczak commented on modules/Settings/Proxy/actions/ConfigProxySaveAjax.php
> +						if ($request->getRaw($fieldName) === '1') {
getBoolen

2020-06-15 04:53 UTC, rskrzypczak commented on modules/Settings/Proxy/actions/ConfigProxySaveAjax.php
> +							$proxyValue = $request->getRaw($fieldName);
changed getRaw

2020-06-15 04:53 UTC, rskrzypczak commented on modules/Settings/Proxy/models/ConfigModule.php
> +	public function getFieldInstanceByName($name)
```suggestion
	public function getFieldInstanceByName(string $name)
```

2020-06-15 04:53 UTC, rskrzypczak commented on modules/Settings/Proxy/views/ConfigProxyEdit.php
> + * @author Arkadiusz So�ek <a.solek@yetiforce.com>
coding

2020-06-15 05:03 UTC, rskrzypczak commented on modules/Settings/Proxy/actions/SaveAjax.php
> + * @package   Settings.Actions
```suggestion
 * @package   Settings.Action
```

2020-06-15 05:03 UTC, rskrzypczak commented on modules/Settings/Proxy/models/Module.php
> + * @package   Settings.Module
```suggestion
 * @package   Settings.Model
```

2020-06-15 05:03 UTC, rskrzypczak commented on modules/Settings/Proxy/models/Module.php
> +	 * @param mixed $name
```suggestion
	 * @param string $name
```

2020-06-15 05:03 UTC, rskrzypczak commented on modules/Settings/Proxy/models/Module.php
> +	 * @return \Settings_Proxy_Module_Model|\Settings_Vtiger_Module_Model
```suggestion
	 * @return self
```
or @return Settings_Proxy_Module_Model

2020-06-15 05:03 UTC, rskrzypczak commented on public_html/layouts/basic/modules/Settings/Proxy/resources/Index.js
> +});
remove this

2020-06-15 05:03 UTC, rskrzypczak commented on public_html/layouts/basic/modules/Settings/Proxy/resources/Index.js
> +				"*[name='proxyConnection'], *[name='proxyProtocol'], *[name='proxyHost'], *[name='proxyPort'], *[name='proxyLogin'], *[name='proxyPassword']"
?

2020-07-09 07:31 UTC, rskrzypczak commented on public_html/layouts/basic/modules/Settings/Proxy/resources/Edit.js
>  				element.on('change', function (e) {
```suggestion
			fieldsChange.find('input, select').on('change', function (e) {
```

2020-07-15 06:08 UTC, rskrzypczak commented on modules/Settings/Proxy/actions/SaveAjax.php
> +					if ($request->getBoolean($fieldName)) {
?

2020-12-28 09:35 UTC, mariuszkrzaczkowski requested changes

2020-12-28 09:35 UTC, mariuszkrzaczkowski commented on layouts/basic/modules/Settings/Proxy/Edit.tpl
> +				{assign var="FIELD_MODEL"
?

2020-12-28 09:35 UTC, mariuszkrzaczkowski commented on modules/Settings/Proxy/actions/SaveAjax.php
> + */
doc

2020-12-28 09:35 UTC, mariuszkrzaczkowski commented on modules/Settings/Proxy/models/Module.php
> + */
doc

2020-12-28 09:35 UTC, mariuszkrzaczkowski commented on modules/Settings/Proxy/models/Module.php
> +	 * Load proxy module list fields.
?

2020-12-28 09:35 UTC, mariuszkrzaczkowski commented on modules/Settings/Proxy/models/Module.php
> +	public function getFieldInstanceByName(string $name)
?

2020-12-28 09:35 UTC, mariuszkrzaczkowski commented on modules/Settings/Proxy/views/Edit.php
> + */
doc

2020-12-28 09:35 UTC, mariuszkrzaczkowski commented on modules/Settings/Proxy/views/Edit.php
> +	 * Process action.
?

2020-12-28 09:35 UTC, mariuszkrzaczkowski commented on modules/Settings/Proxy/views/Edit.php
> +			'modules.Settings.Proxy.resources.Edit',
?

2021-02-01 15:32 UTC, closed without merging