Added mechanism for group adding of records
YetiForceCompany/YetiForceCRM pull request #14509
Opened 2021-04-06 08:25 UTC by areksolek

Added mechanism for group adding of records

2021-04-06 08:32 UTC, mariuszkrzaczkowski requested changes

2021-04-06 08:32 UTC, mariuszkrzaczkowski commented on app/RecordAddsTemplates.php
> +	public static function getTemplatesList()
```suggestion
	public static function getTemplatesList(): array
```

2021-04-06 08:32 UTC, mariuszkrzaczkowski commented on app/RecordAddsTemplates.php
> +	 * @return RecordAddsTemplates\Paccar|null
?

2021-04-06 08:32 UTC, mariuszkrzaczkowski commented on app/RecordAddsTemplates.php
> +				$instance = static::getInstance("\\App\\RecordAddsTemplates\\$fileName");
```suggestion
				$instance = static::getInstance($fileName);
```

2021-04-06 08:32 UTC, mariuszkrzaczkowski commented on modules/Vtiger/views/RecordAddsTemplates.php
> +		$this->recordAddsInstance = \App\RecordAddsTemplates::getInstance("\\App\\RecordAddsTemplates\\{$request->getByType('recordAddsType', 'ClassName')}");
```suggestion
		$this->recordAddsInstance = \App\RecordAddsTemplates::getInstance($request->getByType('recordAddsType', 'ClassName'));
```

2021-04-06 08:32 UTC, mariuszkrzaczkowski commented on modules/Vtiger/views/RecordAddsTemplates.php
> +	public function checkPermission(App\Request $request)
add \App\Config::main('isActiveRecordTemplate')

2021-04-06 08:32 UTC, mariuszkrzaczkowski commented on modules/Vtiger/views/RecordAddsTemplates.php
> +	public function getModalScripts(App\Request $request)
?

2021-04-06 08:32 UTC, mariuszkrzaczkowski commented on public_html/layouts/basic/modules/Vtiger/resources/RecordAddsTemplates.js
> +		 * @param modalContainer
?

2021-04-06 08:32 UTC, mariuszkrzaczkowski commented on public_html/layouts/basic/modules/Vtiger/resources/RecordAddsTemplates.js
> +		 * @param container
?

2021-04-09 06:54 UTC, mariuszkrzaczkowski requested changes

2021-04-09 06:54 UTC, mariuszkrzaczkowski commented on app/RecordAddsTemplates.php
> +	 * @return RecordAddsTemplates\Object
```suggestion
	 * @return Object
```

2021-04-09 06:54 UTC, mariuszkrzaczkowski commented on layouts/basic/modules/Vtiger/RecordAddsTemplates.tpl
> +<!-- tpl-Base-RecordAddsTemplates -->
```suggestion
<!-- tpl-Base-Modals-RecordAddsTemplates -->
```

2021-04-09 06:54 UTC, mariuszkrzaczkowski commented on layouts/basic/modules/Vtiger/BodyHeader.tpl
> +														<a class="showModal text-decoration-none u-fs-sm text-secondary  d-block" data-url="index.php?module={$QUALIFIED_MODULE}&view=RecordAddsTemplates&recordAddsType={$TEMPLATE_VALUE['templa
$QUALIFIED_MODULE ?

2021-04-09 06:54 UTC, mariuszkrzaczkowski commented on app/RecordAddsTemplates.php
> +					$listTemplates[] = ['templateName' => $fileName, 'label' => $instance->label, 'icon' => $instance->icon];
```suggestion
					$listTemplates[] = static::getInstance($fileName);
```

2021-04-09 06:54 UTC, mariuszkrzaczkowski commented on modules/Vtiger/actions/RecordAddsTemplates.php
> +	/** @var \App\RecordAddsTemplates\Object Record adds instance. */
```suggestion
	/** @var Object Record adds instance. */
```

2021-04-09 06:54 UTC, mariuszkrzaczkowski commented on layouts/basic/modules/Vtiger/BodyHeader.tpl
> +								<a class="c-header__btn ml-2 showModal btn-light btn js-popover-tooltip" role="button" data-url="index.php?module={$QUALIFIED_MODULE}&view=RecordAddsTemplates&recordAddsType={$LIST_TEMPLATES[
$QUALIFIED_MODULE ?

2021-04-09 06:54 UTC, mariuszkrzaczkowski commented on modules/Vtiger/actions/RecordAddsTemplates.php
> +	public function process(Request $request)
```suggestion
	public function process(Request $request): void
```

2021-04-09 06:54 UTC, mariuszkrzaczkowski commented on modules/Vtiger/views/RecordAddsTemplates.php
> +	/** @var \App\RecordAddsTemplates\Object Record adds instance. */
```suggestion
	/** @var Object Record adds instance. */
```

2021-04-09 06:54 UTC, mariuszkrzaczkowski commented on modules/Vtiger/views/RecordAddsTemplates.php
> +	public function process(App\Request $request)
```suggestion
	public function process(App\Request $request):void
```

2021-04-09 06:54 UTC, mariuszkrzaczkowski commented on modules/Vtiger/views/RecordAddsTemplates.php
> +		$viewer->view('RecordAddsTemplates.tpl');
```suggestion
		$viewer->view('Modals/RecordAddsTemplates.tpl');
```

2021-04-09 06:54 UTC, mariuszkrzaczkowski commented on modules/Vtiger/views/RecordAddsTemplates.php
> +		$viewer->assign('SCRIPTS', $this->getModalScripts($request));
?

2021-04-09 06:54 UTC, mariuszkrzaczkowski commented on modules/Vtiger/views/RecordAddsTemplates.php
> +		$viewer->assign('MODULE_NAME', $request->getModule());
?

2021-04-09 06:54 UTC, mariuszkrzaczkowski commented on public_html/layouts/basic/modules/Vtiger/resources/RecordAddsTemplates.js
> +					params.module = formSerializeData.module;
?

2021-04-09 06:54 UTC, mariuszkrzaczkowski commented on public_html/layouts/basic/modules/Vtiger/resources/RecordAddsTemplates.js
> +					params.recordAddsType = formSerializeData.recordAddsType;
?

2021-04-09 06:54 UTC, mariuszkrzaczkowski commented on public_html/layouts/basic/modules/Vtiger/resources/RecordAddsTemplates.js
> +				let params = {};
```suggestion
				let params = {action: 'RecordAddsTemplates', recordAddsType: ...};
```

2021-04-12 04:39 UTC, rskrzypczak commented on modules/Settings/Vtiger/models/Field.php
> -	public $referenceList = [];
why you removed this?

2021-04-12 08:07 UTC, mariuszkrzaczkowski approved these changes

2021-04-12 08:08 UTC, merged