Added new IBAN uitype
YetiForceCompany/YetiForceCRM pull request #14831
Opened 2021-06-13 09:54 UTC by konadrian

To test this add a field with 329 uitype and add to the fieldparams 
$fieldParams = ['country' => 'PL', 'sortCode' => '10500161', 'clientId' => '5555', 'conditions' => [
	'legal_form:PLL_NATURAL_PERSON:pesel',
	'defaultValue:vat_id'
], 'clientIdPattern' => 'NNNNNNNNNNNN'];

{"country":"PL","sortCode":"10500161","clientId":"5555","conditions":["legal_form:PLL_NATURAL_PERSON:pesel","defaultValue::vat_id"],"clientIdPattern":"NNNNNNNNNNNN"}

2021-06-15 04:29 UTC, rskrzypczak requested changes

2021-06-15 04:29 UTC, rskrzypczak commented on modules/Vtiger/uitypes/IBAN.php
> +		var_dump($value);
?

2021-06-15 04:29 UTC, rskrzypczak commented on modules/Vtiger/uitypes/IBAN.php
> +		return false;
?

2021-06-15 04:29 UTC, rskrzypczak commented on modules/Vtiger/uitypes/IBAN.php
> +			$clientPattern[$charPosition];
?

2021-06-15 04:29 UTC, rskrzypczak commented on app/Conditions/QueryFields/IBANField.php
> +namespace App\Conditions\QueryFields;
Add for App\Conditions\RecordFields to

2021-06-15 11:24 UTC, mariuszkrzaczkowski commented on composer.json
> +    "globalcitizen/php-iban": "4.0.0"
```suggestion
    "globalcitizen/php-iban": "^4.0.0"
```

2021-06-16 04:26 UTC, merged

2021-06-16 05:57 UTC, mariuszkrzaczkowski commented on app/Fields/Iban.php
> + * Iban class.
?

2021-06-16 05:57 UTC, mariuszkrzaczkowski commented on app/Fields/Iban.php
> +	public function getIBANValue(array $fieldParams, array $recordData): string
getIBANValue ?

$recordData  >>  $recordModel

2021-06-16 05:57 UTC, mariuszkrzaczkowski commented on app/Fields/Iban.php
> +			$countryIBANLength = $this->countryIBAN->IBANLength();
countryIBANLength  >> countryIbanLength

2021-06-16 05:57 UTC, mariuszkrzaczkowski commented on app/Fields/Iban.php
> +			$checkSumValueForCreateIBAN = '00';
checkSumValueForCreateIBAN  > checkSumValueForCreateIban

2021-06-16 05:57 UTC, mariuszkrzaczkowski commented on app/Fields/Iban.php
> +		return isset($this->fieldParams['country']) && isset($this->fieldParams['sortCode'], $this->fieldParams['clientId'], $this->fieldParams['conditions']);
?

2021-06-16 05:57 UTC, mariuszkrzaczkowski commented on install/install_schema/scheme.sql
> +SQLyog Ultimate v13.0.0 (64 bit)
???

2021-06-16 05:57 UTC, mariuszkrzaczkowski commented on modules/Vtiger/handlers/AutoFillIban.php
> + * Vtiger_AutoFillIban_Handler class.
?

2021-06-16 05:57 UTC, mariuszkrzaczkowski commented on modules/Vtiger/handlers/AutoFillIban.php
> +	public function entityBeforeSave(App\EventHandler $eventHandler)
public function entityBeforeSave(App\EventHandler $eventHandler): void

2021-06-16 05:57 UTC, mariuszkrzaczkowski commented on modules/Vtiger/handlers/AutoFillIban.php
> +		$ibanUiType = 329;
static

2021-06-16 05:57 UTC, mariuszkrzaczkowski commented on modules/Vtiger/handlers/AutoFillIban.php
> +					$fieldParams = $moduleIbanField->getFieldParams();
?

2021-06-16 05:57 UTC, mariuszkrzaczkowski commented on modules/Vtiger/handlers/AutoFillIban.php
> +					$ibanValue = $ibanField->getIBANValue($fieldParams, $recordData);
?

2021-06-16 06:04 UTC, mariuszkrzaczkowski commented on app/Fields/Iban.php
> +		return isset($this->fieldParams['country']) && isset($this->fieldParams['sortCode'], $this->fieldParams['clientId'], $this->fieldParams['conditions']);
throw Exceptions

2021-06-16 06:10 UTC, mariuszkrzaczkowski commented on modules/Vtiger/handlers/AutoFillIban.php
> +					$ibanValue = $ibanField->getIBANValue($fieldParams, $recordData);
?