Added filtering on empty values.
YetiForceCompany/YetiForceCRM pull request #15191
Opened 2021-09-16 13:19 UTC by areksolek

Added filtering on empty values.

2021-09-20 11:55 UTC, mariuszkrzaczkowski requested changes

2021-09-20 11:55 UTC, mariuszkrzaczkowski commented on layouts/basic/modules/Vtiger/List/Field/Base.tpl
> +{assign var=READONLY value=$FIELD_MODEL->getReadOnlyFieldInSearchParams($CONSTANT_READONLY, $TEMPORARILY_READONLY)}
?

2021-09-20 11:55 UTC, mariuszkrzaczkowski commented on layouts/basic/modules/Vtiger/ListViewContents.tpl
> +	<input type="hidden" class="js-temporarily-readonly" data-js="value" value='{$TEMPORARILY_READONLY}'/>
?

2021-09-22 05:07 UTC, rskrzypczak requested changes

2021-09-22 05:07 UTC, rskrzypczak commented on layouts/basic/modules/Vtiger/ListViewContents.tpl
> +	<input type="hidden" class="js-locked-fields" data-js="value" value='{$SEARCH_COLUMN_EMPTI_CONDITION}'/>
SEARCH_COLUMN_EMPT**Y**_CONDITION

2021-09-22 05:07 UTC, rskrzypczak commented on modules/Vtiger/models/Field.php
> +		return true;
return empty($this->get('disabledField'));

2021-09-22 05:07 UTC, rskrzypczak commented on modules/Vtiger/models/ListView.php
> +					$fieldModel = $moduleModel[$value['field_name']];
$moduleModel->getFieldByName()

2021-09-22 05:07 UTC, rskrzypczak commented on modules/Vtiger/models/RelationListView.php
> +			foreach ($request->getArray('fieldsLocked', 'AlnumExtended') as $value) {
AlnumExtended ?

2021-09-22 05:07 UTC, rskrzypczak commented on modules/Vtiger/models/ListView.php
> +				$fieldModel->set('fromOutsideList', false);
?

2021-09-22 09:40 UTC, mariuszkrzaczkowski requested changes

2021-09-22 09:40 UTC, mariuszkrzaczkowski commented on modules/Vtiger/models/Field.php
> +		return empty($this->get('disabledField'));
```suggestion
		return empty($this->get('emptyValueSearchInView'));
```

2021-09-22 09:40 UTC, mariuszkrzaczkowski commented on modules/Vtiger/models/ListView.php
> +		foreach ($this->getArray('search_params') as $values) {
?

2021-09-22 09:40 UTC, mariuszkrzaczkowski commented on modules/Vtiger/models/ListView.php
> +	public function fieldsPermanentlyBlocked(): void
```suggestion
	public function loadBlockedFields(): void
```

2021-09-22 09:40 UTC, mariuszkrzaczkowski commented on modules/Vtiger/models/ListView.php
> +	public function fieldsPermanentlyBlocked(): void
?

2021-09-22 09:40 UTC, mariuszkrzaczkowski commented on modules/Vtiger/models/ListView.php
> +				$fieldModel->set('fromOutsideList', false);
?

2021-09-22 09:40 UTC, mariuszkrzaczkowski commented on modules/Vtiger/models/ListView.php
> +					$fieldModel->set('fromOutsideList', true);
?

2021-09-22 09:40 UTC, mariuszkrzaczkowski commented on modules/Vtiger/views/List.php
> +			$this->listViewModel->lockedFields($request);
?

2021-09-22 09:40 UTC, mariuszkrzaczkowski commented on modules/Vtiger/views/List.php
> +		$viewer->assign('SEARCH_COLUMN_EMPTY_CONDITION', $request->isEmpty('fieldsLocked', true) ? false : \App\Json::encode($request->getArray('fieldsLocked')));
?

2021-09-22 09:40 UTC, mariuszkrzaczkowski commented on modules/Vtiger/views/List.php
> +		$viewer->assign('SEARCH_COLUMN_EMPTY_CONDITION', $request->isEmpty('fieldsLocked', true) ? false : \App\Json::encode($request->getArray('fieldsLocked')));
lockedFields

2021-09-22 09:40 UTC, mariuszkrzaczkowski commented on public_html/layouts/basic/modules/Vtiger/resources/ListSearch.js
> +		registerListSearchIfEmptyValue: function () {
```suggestion
		registerListSearchEmptyValue: function () {
```

2021-09-22 09:40 UTC, mariuszkrzaczkowski commented on public_html/layouts/basic/modules/Vtiger/resources/ListSearch.js
> +			let thisInstance = this;
```suggestion
			const self = this;
```

2021-09-22 09:40 UTC, mariuszkrzaczkowski commented on public_html/layouts/basic/modules/Vtiger/resources/RecordsList.js
> +				fieldsLocked: this.container.find('.js-locked-fields').val(),
lockedFields

2021-09-22 09:40 UTC, mariuszkrzaczkowski commented on public_html/layouts/basic/modules/Vtiger/resources/RecordsList.js
> +				params['search_params'] = this.container.find('#search_params').val();
?

2021-09-22 09:45 UTC, mariuszkrzaczkowski commented on modules/Vtiger/models/Field.php
> +	public function emptyValueSearchInView(): bool
```suggestion
	public function searchlockedFields(): bool
```

2021-09-22 13:09 UTC, mariuszkrzaczkowski requested changes

2021-09-22 13:09 UTC, mariuszkrzaczkowski commented on layouts/basic/modules/Vtiger/List/Field/Base.tpl
> +			{/if} class="listSearchContributor form-control" value="{$SEARCH_VALUE}" title='{$LABEL['label']}' data-fieldinfo='{$FIELD_INFO|escape}' {if !$FIELD_MODEL->searchlockedFields() || !$FIELD_MODEL->i
searchLockedFields

2021-09-22 13:09 UTC, mariuszkrzaczkowski commented on modules/Vtiger/models/Field.php
> +		return empty($this->get('searchlockedFields'));
searchLockedFields

2021-09-22 13:09 UTC, mariuszkrzaczkowski commented on modules/Vtiger/models/Field.php
> +		if ($this->get('fromOutsideList') || $this->get('fieldsPermanentlyBlocked')) {
?

2021-09-23 07:23 UTC, mariuszkrzaczkowski commented on public_html/layouts/basic/modules/Vtiger/resources/ListSearch.js
> +		 * Column name from last search.
/**
 * @type {string}
 */

2021-09-23 07:23 UTC, mariuszkrzaczkowski commented on public_html/layouts/basic/modules/Vtiger/resources/ListSearch.js
> +		 * Column name from last search.
https://www.typescriptlang.org/docs/handbook/jsdoc-supported-types.html

2021-09-23 07:30 UTC, merged