Improved filtering on empty values.
YetiForceCompany/YetiForceCRM pull request #15265
Opened 2021-10-05 14:33 UTC by areksolek

Improved filtering on empty values.

2021-10-05 15:16 UTC, ghost commented
## Black Duck Security Report

Merging #15265 into developer will not change security risk.

[Click here to see full report](https://copilot.blackducksoftware.com/github/repos/YetiForceCompany/YetiForceCRM/pull-requests/15265)

2021-10-06 12:10 UTC, mariuszkrzaczkowski commented on layouts/basic/modules/Vtiger/List/Field/Base.tpl
> +					<input type="checkbox" class="js-empty-value" {if !$FIELD_MODEL->searchLockedEmptyFields()} checked {/if} {if !$FIELD_MODEL->isActiveSearchView()}disabled{/if} >
```suggestion
					<input type="checkbox" class="js-empty-value" {if !$FIELD_MODEL->searchLockedEmptyFields()}checked{/if} {if !$FIELD_MODEL->isActiveSearchView()}disabled{/if} >
```

2021-10-06 12:17 UTC, mariuszkrzaczkowski requested changes

2021-10-06 12:17 UTC, mariuszkrzaczkowski commented on layouts/basic/modules/Vtiger/ListViewContents.tpl
> +	<input type="hidden" class="js-empty-fields" data-js="value" value="{\App\Purifier::encodeHtml($LOCKED_FIELDS)}"/>
```suggestion
	<input type="hidden" class="js-empty-fields" data-js="value" value="{\App\Purifier::encodeHtml(\App\Json::encode($LOCKED_FIELDS))}"/>
```

2021-10-06 12:17 UTC, mariuszkrzaczkowski commented on modules/Vtiger/views/List.php
> +		$viewer->assign('LOCKED_EMPTY_FIELDS', $request->isEmpty('lockedEmptyFields', true) ? false : \App\Json::encode($request->getArray('lockedEmptyFields')));
```suggestion
		$viewer->assign('LOCKED_EMPTY_FIELDS', $request->isEmpty('lockedEmptyFields', true) ? []: $request->getArray('lockedEmptyFields'));
```

2021-10-06 12:17 UTC, mariuszkrzaczkowski commented on modules/Vtiger/views/RecordsList.php
> +		$viewer->assign('LOCKED_EMPTY_FIELDS', $request->isEmpty('lockedEmptyFields', true) ? false : \App\Json::encode($request->getArray('lockedEmptyFields')));
```suggestion
		$viewer->assign('LOCKED_EMPTY_FIELDS', $request->isEmpty('lockedEmptyFields', true) ? [] : $request->getArray('lockedEmptyFields'));
```

2021-10-06 12:17 UTC, mariuszkrzaczkowski commented on modules/Vtiger/views/RelatedList.php
> +		$viewer->assign('LOCKED_EMPTY_FIELDS', $request->isEmpty('lockedEmptyFields', true) ? false : \App\Json::encode($request->getArray('lockedEmptyFields')));
?

2021-10-06 12:17 UTC, mariuszkrzaczkowski commented on layouts/basic/modules/Vtiger/RelatedList.tpl
> +	<input type="hidden" class="js-empty-fields" data-js="value" value="{\App\Purifier::encodeHtml($LOCKED_EMPTY_FIELDS)}"/>
?

2021-10-06 12:17 UTC, mariuszkrzaczkowski commented on layouts/basic/modules/Vtiger/Modals/RecordsList.tpl
> +		<input type="hidden" class="js-empty-fields" data-js="value" value="{\App\Purifier::encodeHtml($LOCKED_EMPTY_FIELDS)}"/>
?

2021-10-07 07:39 UTC, merged