Added Tiles view
YetiForceCompany/YetiForceCRM pull request #15981
Opened 2022-04-22 12:44 UTC by konadrian

Added Tiles view
![Tiles](https://user-images.githubusercontent.com/3193498/164716555-d0a930d4-0985-4eed-a0ce-a782514b18e2.gif)

2022-04-28 06:36 UTC, rskrzypczak requested changes

2022-04-28 06:36 UTC, rskrzypczak commented on languages/en-US/_Base.json
> +    "LBL_BIG_TILE": "Big"
LBL_TILES_...

2022-04-28 06:36 UTC, rskrzypczak commented on layouts/basic/modules/Vtiger/TilesHeader.tpl
> +					</div>
new template

2022-04-28 06:36 UTC, rskrzypczak commented on layouts/basic/modules/Vtiger/TilesLeftSide.tpl
> +	<!-- tpl-Base-TilesLeftSide -->
file name

2022-04-28 06:36 UTC, rskrzypczak commented on layouts/basic/modules/Vtiger/TilesPreProcess.tpl
> +				{include file=\App\Layout::getTemplatePath('TilesHeader.tpl', $MODULE)}
up

2022-04-28 06:36 UTC, rskrzypczak commented on modules/Vtiger/models/Module.php
> +		if ($this->isPermitted('Tiles')) {
```suggestion
		if ($this->isPermitted('TilesView')) {
```

2022-04-28 06:36 UTC, rskrzypczak commented on modules/Vtiger/models/Record.php
> +		$uitypeModelMethod = method_exists($uitypeModel, 'getTilesDisplayValue') ? 'getTilesDisplayValue' : 'getListViewDisplayValue';
getTilesDisplayValue add to global base uitype model

2022-04-28 06:36 UTC, rskrzypczak commented on layouts/basic/modules/Vtiger/TilesContents.tpl
> +														{/if}
```suggestion
           {$LISTVIEW_ENTRY->getTilesDisplayValue($LISTVIEW_HEADER)}
```

2022-04-28 06:36 UTC, rskrzypczak commented on modules/Vtiger/uitypes/MultiImage.php
> +		if (!$value) {
```suggestion
		if (!$value || !($value = \App\Json::decode($value)) {
```

2022-04-28 06:36 UTC, rskrzypczak commented on modules/Vtiger/uitypes/MultiImage.php
> +		$carouselId = "tileCarousel{$record}";
\App\Layout::getUniqueId(.. ,$record.'IM-');

2022-04-28 06:36 UTC, rskrzypczak commented on modules/Vtiger/views/Tiles.php
> +		if (!Users_Privileges_Model::getCurrentUserPrivilegesModel()->hasModuleActionPermission($request->getModule(), 'Tiles')) {
check

2022-04-28 06:36 UTC, rskrzypczak commented on modules/Vtiger/views/Tiles.php
> +class Vtiger_Tiles_View extends Vtiger_Index_View
check extends Vtiger_List_view

2022-04-28 06:36 UTC, rskrzypczak commented on modules/Vtiger/views/Tiles.php
> +		$moduleName = $request->getModule();
check parent::initialize..

2022-04-28 06:36 UTC, rskrzypczak commented on modules/Vtiger/views/Tiles.php
> +		$viewer->view('TilesContents.tpl', $moduleName);
check

public function ..TplName(App\Request $request)
	{
		return 'TilesContents.tpl';
	}

2022-04-28 06:36 UTC, rskrzypczak commented on modules/Vtiger/views/Tiles.php
> +		$moduleName = $request->getModule();
parent::

2022-04-28 06:36 UTC, rskrzypczak commented on public_html/layouts/basic/modules/Vtiger/resources/List.js
> +				if ('Tiles' === app.getViewName()) {
?

2022-04-28 06:36 UTC, rskrzypczak commented on public_html/layouts/basic/modules/Vtiger/resources/Tiles.js
> +			let thisInstance = this;
```suggestion

```

2022-04-28 06:36 UTC, rskrzypczak commented on public_html/layouts/basic/modules/Vtiger/resources/Tiles.js
> +					thisInstance.setHeightOfTiles(thisInstance.contentContainer);
```suggestion
					this.setHeightOfTiles(this.contentContainer);
```

2022-04-28 06:36 UTC, rskrzypczak commented on public_html/layouts/basic/modules/Vtiger/resources/Tiles.js
> +		setHeightOfTiles: function () {
?

2022-04-28 06:36 UTC, rskrzypczak commented on public_html/layouts/basic/styles/components/_Global.scss
> +	z-index: 999;
```suggestion

```

2022-05-04 07:23 UTC, rskrzypczak requested changes

2022-05-04 07:23 UTC, rskrzypczak commented on config/ConfigTemplates.php
> +			'description' => 'Should the breadcrumb menu have href enabled? true = enabled, false = off',
Desc

2022-05-04 07:23 UTC, rskrzypczak commented on layouts/basic/modules/Vtiger/TilesActions.tpl
> +								{include file=\App\Layout::getTemplatePath('ButtonLink.tpl', $MODULE) BUTTON_VIEW='listViewBasic' BTN_CLASS='btn-xs'}
```suggestion
								{include file=\App\Layout::getTemplatePath('ButtonLink.tpl', $MODULE_NAME) BUTTON_VIEW='listViewBasic' BTN_CLASS='btn-xs'}
```

2022-05-04 07:23 UTC, rskrzypczak commented on layouts/basic/modules/Vtiger/TilesContents.tpl
> +		</table>
table move to the new shared file

2022-05-04 07:23 UTC, rskrzypczak commented on layouts/basic/modules/Vtiger/TilesContents.tpl
> +														<small> {$LISTVIEW_ENTRY->getListViewDisplayValue($LISTVIEW_HEADER)} </small>
?

2022-05-04 07:23 UTC, rskrzypczak commented on modules/Vtiger/models/Record.php
> +	 * @return mixed
```suggestion
	 * @return string
```

2022-05-04 07:23 UTC, rskrzypczak commented on modules/Vtiger/models/Record.php
> +				return $this->ext[$field->get('source_field_name')][$field->getModuleName()]->getListViewDisplayValue($field, $rawText);
?

2022-05-04 07:31 UTC, rskrzypczak requested changes

2022-05-04 07:31 UTC, rskrzypczak commented on modules/Vtiger/uitypes/Base.php
> +	 * @return mixed
```suggestion
	 * @return string
```

2022-05-04 07:31 UTC, rskrzypczak commented on modules/Vtiger/uitypes/MultiImage.php
> +		if (!($value = \App\Json::decode($value)) && !$value) {
```suggestion
		if (!$value || !($value = \App\Json::decode($value))) {
```

2022-05-04 07:31 UTC, rskrzypczak commented on modules/Vtiger/uitypes/MultiImage.php
> +			$carouselId = App\Layout::getUniqueId("IC{$record}");
?

2022-05-04 07:31 UTC, rskrzypczak commented on modules/Vtiger/uitypes/MultiImage.php
> +				<img class="d-block  carousel-image" src="' . $this->getImageUrl($item['key'], $record) . '" alt="First slide">
remove unnecessary spaces

2022-05-04 07:31 UTC, rskrzypczak commented on public_html/layouts/basic/modules/Vtiger/resources/List.js
> +			const thisInstance = this;
?

2022-05-04 07:31 UTC, rskrzypczak commented on public_html/layouts/basic/modules/Vtiger/resources/Tiles.js
> +				$('#totalPageCount').text('');
container

2022-05-04 09:40 UTC, mariuszkrzaczkowski commented on layouts/basic/modules/Vtiger/TilesSize.tpl
> +			<a class=" dropdown-item js-tile-size" data-tile-size="small" href="#">{\App\Language::translate('LBL_TILE_SMALL', $MODULE_NAME)}</a>
```suggestion
			<a class="dropdown-item js-tile-size" data-tile-size="small" href="#">{\App\Language::translate('LBL_TILE_SMALL', $MODULE_NAME)}</a>
```

2022-05-04 09:42 UTC, mariuszkrzaczkowski commented on public_html/layouts/basic/styles/Main.scss
> +@import "pages/Tiles";
```suggestion
@import "pages/_Tiles";
```

2022-05-04 10:02 UTC, merged