Corrected the display of values for the image field.
YetiForceCompany/YetiForceCRM pull request #16005
Opened 2022-04-28 14:02 UTC by areksolek

Corrected the display of values for the image field.

2022-04-28 14:05 UTC, ghost commented
## Black Duck Security Report

Merging #16005 into developer will not change security risk.

[Click here to see full report](https://copilot.blackducksoftware.com/github/repos/YetiForceCompany/YetiForceCRM/pull-requests/16005)

2022-04-28 15:45 UTC, rskrzypczak requested changes

2022-04-28 15:45 UTC, rskrzypczak commented on modules/Vtiger/uitypes/MultiImage.php
> +				$result .= \App\TextParser::textTruncate($val['name'], $length) . ', ';
raw - no truncate

2022-04-28 15:45 UTC, rskrzypczak commented on modules/Vtiger/uitypes/MultiImage.php
> +		for ($i = 0; $i < $len; ++$i) {
?

2022-04-29 07:02 UTC, rskrzypczak commented on modules/Vtiger/uitypes/MultiImage.php
> +			return \App\Purifier::encodeHtml(trim($rawText && $length ? \App\TextParser::textTruncate($result, $length) : $result, "\n\t ,"));
```suggestion
			return \App\Purifier::encodeHtml($length ? \App\TextParser::textTruncate($result, $length) : $result, "\n\t ,"));
```

2022-04-29 07:02 UTC, merged