Added possibiliy of sorting tasks and actions in workflows
YetiForceCompany/YetiForceCRM pull request #16028
Opened 2022-05-04 15:31 UTC by konadrian

Added possibiliy of sorting tasks and actions in workflows

2022-05-04 15:33 UTC, ghost commented
## Black Duck Security Report

Merging #16028 into developer will not change security risk.

[Click here to see full report](https://copilot.blackducksoftware.com/github/repos/YetiForceCompany/YetiForceCRM/pull-requests/16028)

2022-05-06 08:16 UTC, rskrzypczak requested changes

2022-05-06 08:16 UTC, rskrzypczak commented on layouts/basic/modules/Settings/Workflows/ListViewHeader.tpl
> +					<select class="select2 form-control js-module-filter" id="moduleFilter">
js-module-filter ?

2022-05-06 08:16 UTC, rskrzypczak commented on modules/Settings/Vtiger/views/List.php
> +			$sourceModule = $request->getByType('sourceModule', 2);
2 => \App\P..::..

2022-05-06 08:16 UTC, rskrzypczak commented on modules/com_vtiger_workflow/VTWorkflowManager.php
> +				'sequence' => $wf->sequence,
```suggestion
				'sequence' => (int) $wf->sequence,
```

2022-05-06 08:16 UTC, rskrzypczak commented on public_html/layouts/basic/modules/Settings/Workflows/resources/List.js
> +					orderby: 'sequence'
?

2022-05-06 08:16 UTC, rskrzypczak commented on public_html/layouts/basic/modules/Settings/Workflows/resources/List.js
> +		 * @returns [array]
[] ?

2022-05-11 07:56 UTC, merged