add Performance to System Tools
YetiForceCompany/YetiForceCRM pull request #16046
Opened 2022-05-16 13:27 UTC by rembiesa

2022-05-16 13:30 UTC, ghost commented
## Black Duck Security Report

Merging #16046 into developer will not change security risk.

[Click here to see full report](https://copilot.blackducksoftware.com/github/repos/YetiForceCompany/YetiForceCRM/pull-requests/16046)

2022-05-16 14:10 UTC, rskrzypczak requested changes

2022-05-16 14:10 UTC, rskrzypczak commented on languages/en-US/_Base.json
> +    "LBL_PERFORMANCE": "Performance",
Move all labels to correct file (\Settings\ConfigEditor.json)

2022-05-16 14:10 UTC, rskrzypczak commented on modules/Settings/ConfigEditor/models/Module.php
> +	/** {@inheritdoc} */
inherited after what?

2022-05-17 06:17 UTC, rskrzypczak commented on layouts/basic/modules/Settings/ConfigEditor/Detail.tpl
>  				{include file=\App\Layout::getTemplatePath('Relation.tpl', $QUALIFIED_MODULE)}
```suggestion
				{include file=\App\Layout::getTemplatePath('ConfigTamplate.tpl', $QUALIFIED_MODULE) CONFIG_NAME='Relation'}
```

2022-05-17 08:38 UTC, merged