Fixed queue popupReference error
YetiForceCompany/YetiForceCRM pull request #16119
Opened 2022-05-30 13:33 UTC by rembiesa

2022-05-30 13:35 UTC, ghost commented
## Black Duck Security Report

Merging #16119 into developer will not change security risk.

[Click here to see full report](https://copilot.blackducksoftware.com/github/repos/YetiForceCompany/YetiForceCRM/pull-requests/16119)

2022-05-31 04:08 UTC, rskrzypczak commented on modules/Vtiger/uitypes/ChangesJson.php
> +		foreach ($value['changes'] as $fieldName => $val) {
?

2022-05-31 06:27 UTC, rskrzypczak requested changes

2022-05-31 06:27 UTC, rskrzypczak commented on modules/Vtiger/uitypes/ChangesJson.php
> +		$moduleModel = Vtiger_Module_Model::getInstance($request->get('module'));
```suggestion
		$moduleModel = Vtiger_Module_Model::getInstance($request->getModule());
```

2022-05-31 06:27 UTC, rskrzypczak commented on modules/Vtiger/uitypes/ChangesJson.php
> +			if ($moduleModel->getFieldByName($fieldName)) {
->getFields() : array_kays
$value['changes'] = array_intersect_key($value['changes'], $->getFields());

2022-05-31 09:08 UTC, merged