Web Content Accessibility Guidelines improvments
YetiForceCompany/YetiForceCRM pull request #16126
Opened 2022-06-01 13:53 UTC by rembiesa

2022-06-01 13:55 UTC, ghost commented
## Black Duck Security Report

Merging #16126 into developer will not change security risk.

[Click here to see full report](https://copilot.blackducksoftware.com/github/repos/YetiForceCompany/YetiForceCRM/pull-requests/16126)

2022-06-02 05:14 UTC, rskrzypczak requested changes

2022-06-02 05:14 UTC, rskrzypczak commented on layouts/basic/modules/Vtiger/List/Field/Base.tpl
> +				<input type="text" name="{$FIELD_MODEL->getName()}" aria-label="{$FIELD_MODEL->getName()}" {if !empty($FIELD_MODEL->get('source_field_name'))} data-source-field-name="{$FIELD_MODEL->get('source_f
?

2022-06-02 05:14 UTC, rskrzypczak commented on layouts/basic/modules/Vtiger/List/Field/Base.tpl
> +				<input type="text" name="{$FIELD_MODEL->getName()}" aria-label="{$FIELD_MODEL->getName()}" {if !empty($FIELD_MODEL->get('source_field_name'))} data-source-field-name="{$FIELD_MODEL->get('source_f
?

2022-06-02 05:14 UTC, rskrzypczak commented on layouts/basic/modules/Vtiger/ListViewContents.tpl
> +								<span aria-label="{\App\Language::translate('LBL_SORTING_SETTINGS')}" class="fas fa-sort"></span>
?

2022-06-02 07:49 UTC, rskrzypczak requested changes

2022-06-02 07:49 UTC, rskrzypczak commented on layouts/basic/modules/Vtiger/List/Field/Base.tpl
> +				<input type="text" name="{$FIELD_MODEL->getName()}" role="input" {if !empty($FIELD_MODEL->get('source_field_name'))} data-source-field-name="{$FIELD_MODEL->get('source_field_name')}" data-module-
?

2022-06-02 07:49 UTC, rskrzypczak commented on layouts/basic/modules/Vtiger/Pagination.tpl
> +						<a class="page-link" aria-label="{\App\Language::translate('LBL_CURRENT_PAGE')}{$PAGE_INDEX}" href="#">{$PAGE_INDEX}</a>
?

2022-06-02 07:49 UTC, rskrzypczak commented on layouts/basic/modules/Vtiger/Pagination.tpl
> +					<a class="page-link" aria-label="{\App\Language::translate('LBL_CURRENT_PAGE')}{$PAGE_INDEX}" href="#">{$PAGE_COUNT}</a>
?

2022-06-02 09:02 UTC, rskrzypczak requested changes

2022-06-02 09:02 UTC, rskrzypczak commented on layouts/basic/modules/Vtiger/Pagination.tpl
> +					<a class="page-link" aria-label="{\App\Language::translate('LBL_CURRENT_PAGE')} {$PAGE_COUNT}" href="#">{$PAGE_COUNT}</a>
?

2022-06-02 09:02 UTC, rskrzypczak commented on layouts/basic/modules/Vtiger/ListViewContents.tpl
> +								<span aria-label="{\App\Language::translate('LBL_SORTING_SETTINGS')}" class="fas fa-sort"></span>
span? 
move to button

2022-06-02 11:23 UTC, rskrzypczak commented on layouts/basic/modules/Vtiger/ListViewContents.tpl
> +							<button type="button" aria-label="{\App\Language::translate('LBL_SORTING_SETTINGS')}" class="ml-2 btn {if !empty($ORDER_BY)}btn-info{else}btn-outline-info{/if} btn-xs js-show-modal"
switch to title

2022-06-02 11:37 UTC, merged