add Date to print page.
YetiForceCompany/YetiForceCRM pull request #16155
Opened 2022-06-10 14:59 UTC by rembiesa

2022-06-10 15:01 UTC, ghost commented
## Black Duck Security Report

Merging #16155 into developer will not change security risk.

[Click here to see full report](https://copilot.blackducksoftware.com/github/repos/YetiForceCompany/YetiForceCRM/pull-requests/16155)

2022-06-13 07:42 UTC, mariuszkrzaczkowski requested changes

2022-06-13 07:42 UTC, mariuszkrzaczkowski commented on layouts/basic/modules/Vtiger/Modals/RecordCollector.tpl
> +		<div class="js-printed-by" style="display: none">
class d-none

2022-06-13 07:42 UTC, mariuszkrzaczkowski commented on languages/en-US/Other/RecordCollector.json
> +    "LBL_POLAND_VAT_PAYER": "Verify VAT taxpayer’s [PL] status ",
?

2022-06-13 07:42 UTC, mariuszkrzaczkowski commented on modules/Vtiger/views/RecordCollector.php
> +		$viewer->assign('USER_MODEL', \App\User::getUserModel(\App\User::getCurrentUserId()));
remove

2022-06-13 07:42 UTC, mariuszkrzaczkowski commented on public_html/layouts/resources/app.js
> +			let printedBy = $('.js-printed-by');
element.closest

2022-06-13 12:24 UTC, mariuszkrzaczkowski commented on layouts/basic/modules/Vtiger/Modals/RecordCollector.tpl
> +			{\App\Language::translate('LBL_PRINTED_BY', 'Other.RecordCollector')} {$USER_MODEL->getName()} {\App\Language::translate('LBL_IN_DAY', 'Other.RecordCollector')} {date($DATE_FORMAT)}
date($DATE_FORMAT) >> App\Fields\DateTime::formatToDisplay('now')

2022-06-14 09:40 UTC, merged