Added second confirmation during deleting product or service
YetiForceCompany/YetiForceCRM pull request #16272
Opened 2022-07-18 16:40 UTC by konadrian

![DeleteInv](https://user-images.githubusercontent.com/3193498/179560532-917f76c3-c765-43ea-a51e-ce7db2e72f8f.gif)

2022-07-19 06:39 UTC, mariuszkrzaczkowski requested changes

2022-07-19 06:39 UTC, mariuszkrzaczkowski commented on modules/Vtiger/models/InventoryDelete.php
> +	private $recordId = 0;
```suggestion
	private $recordId;
```

2022-07-19 06:39 UTC, mariuszkrzaczkowski commented on modules/Vtiger/models/InventoryDelete.php
> +	private $moduleNameForDelete = '';
```suggestion
	private $moduleNameForDelete;
```

2022-07-19 10:04 UTC, ghost commented
## Black Duck Security Report

Merging #16272 into developer will increase security risk!

### Added Components

Low Risk:    1
Clean:       67

### Removed Components

Clean:       52

[Click here to see full report](https://copilot.blackducksoftware.com/github/repos/YetiForceCompany/YetiForceCRM/pull-requests/16272)

2022-08-12 08:45 UTC, mariuszkrzaczkowski commented on modules/Vtiger/models/InventoryDelete.php
> +		$allModules = \vtlib\Functions::getAllModules(false, true);
```suggestion
		$allModules = \vtlib\Functions::getAllModules(true, true);
```

2023-02-15 13:31 UTC, closed without merging