Added working time counter widget.
YetiForceCompany/YetiForceCRM pull request #16316
Opened 2022-08-03 06:57 UTC by areksolek

Added working time counter widget.

2022-08-03 07:46 UTC, rskrzypczak requested changes

2022-08-03 07:46 UTC, rskrzypczak commented on modules/OSSTimeControl/dashboards/TimeCounter.php
> +	public function process(App\Request $request)
docBlock

2022-08-03 07:46 UTC, rskrzypczak commented on public_html/layouts/basic/modules/Vtiger/resources/dashboards/Widget.js
> +		timeStop: '',
docBlock

2022-08-03 07:46 UTC, rskrzypczak commented on public_html/layouts/basic/modules/Vtiger/resources/dashboards/Widget.js
> +			let navigator = container.find('.js-navigator');
Correction of the class name to be more specific for this widget. The current names are too general

2022-08-03 07:46 UTC, rskrzypczak commented on public_html/layouts/basic/modules/Vtiger/resources/dashboards/Widget.js
> +			let instance = this;
remove

2022-08-03 07:46 UTC, rskrzypczak commented on public_html/layouts/basic/modules/Vtiger/resources/dashboards/Widget.js
> +				if (this.sec == 60) {
=== in all

2022-08-03 07:46 UTC, rskrzypczak commented on public_html/layouts/basic/styles/pages/_Dashboard.scss
> +.o-time-counter {
add description

2022-08-03 07:47 UTC, rskrzypczak commented on layouts/basic/modules/OSSTimeControl/dashboards/TimeCounterContents.tpl
> +		<div class="o-time-counter__stopwatch text-center mt-3 js-stopwatch" data-js="container">
_js-stop-watch_ and _js-stopwatch_ ??

2022-08-03 10:57 UTC, rskrzypczak requested changes

2022-08-03 10:57 UTC, rskrzypczak commented on layouts/basic/modules/OSSTimeControl/dashboards/TimeCounter.tpl
> +			{include file=\App\Layout::getTemplatePath('dashboards/WidgetHeaderTitle.tpl', $MODULE_NAME) TITLE=App\Purifier::encodeHtml(App\Language::translate($WIDGET->getTitle(), 'Home'))}
App\Language::translate($WIDGET->getTitle(), 'Home').
'Home'?

2022-08-03 10:57 UTC, rskrzypczak commented on public_html/layouts/basic/modules/Vtiger/resources/dashboards/Widget.js
> +		resetTimerCounter: function (container) {
argument required? 
remove

2022-08-12 08:41 UTC, mariuszkrzaczkowski commented on public_html/layouts/basic/modules/Vtiger/resources/dashboards/Widget.js
> +		/** Hours of the timer */
/** @type ... */

2022-08-12 09:23 UTC, merged