Added new relation type - Multi Reference
YetiForceCompany/YetiForceCRM pull request #17088
Opened 2023-05-17 06:50 UTC by konadrian

![image](https://github.com/YetiForceCompany/YetiForceCRM/assets/3193498/c4c59bfc-9975-43bd-99b8-e70659ef6e46)

2023-05-17 13:33 UTC, rskrzypczak requested changes

2023-05-17 13:33 UTC, rskrzypczak commented on modules/Settings/LayoutEditor/actions/Relation.php
> +			$referenceFieldValues = explode('::', $request->getByType('multi_reference_field', App\Purifier::TEXT));
getExploded()

2023-05-17 13:33 UTC, rskrzypczak commented on modules/Vtiger/models/Relation.php
> +	//** @var int Multi reference   */
```suggestion
	/** @var int Multi reference   */
```

2023-05-17 13:33 UTC, rskrzypczak commented on modules/Vtiger/models/Relation.php
> +	const RELATION_MF = 4;
RELATION_MF RELATION_M**R** ?

2023-05-17 16:00 UTC, mariuszkrzaczkowski commented on modules/Vtiger/models/Relation.php
> +	const RELATION_MF = 4;
RELATION_MR

2023-05-17 16:01 UTC, mariuszkrzaczkowski commented on modules/Vtiger/models/Relation.php
> +			if (in_array($this->getRelationType(), [ static::RELATION_AR , static::RELATION_MF])) {
?

2023-05-17 16:04 UTC, mariuszkrzaczkowski commented on modules/Vtiger/uitypes/MultiReference.php
> +	public static function getFieldsRelatedWithModule(string $moduleName): array
move to modules\Settings\LayoutEditor\models\Module.php

2023-05-17 16:05 UTC, mariuszkrzaczkowski commented on public_html/layouts/basic/modules/Settings/LayoutEditor/resources/LayoutEditor.js
> +						if (typeOption === 'getAttachments') {
switch

2023-05-17 16:41 UTC, konadrian commented on modules/Vtiger/models/Relation.php
> +			if (in_array($this->getRelationType(), [ static::RELATION_AR , static::RELATION_MF])) {
For disable button, unlink relation

2023-05-18 05:24 UTC, rskrzypczak requested changes

2023-05-18 05:24 UTC, rskrzypczak commented on modules/Settings/LayoutEditor/actions/Relation.php
> +			$referenceFieldValues = $request->getExploded('multi_reference_field', '::' . App\Purifier::TEXT);
```suggestion
			$referenceFieldValues = $request->getExploded('multi_reference_field', '::' . App\Purifier::ALNUM);
```

2023-05-18 05:24 UTC, rskrzypczak commented on modules/Settings/LayoutEditor/views/Index.php
> +		$viewer->assign('MODULE_MULTI_REFERENCE_FIELDS', Vtiger_MultiReference_UIType::getFieldsRelatedWithModule($sourceModule));
?

2023-05-18 05:24 UTC, rskrzypczak commented on modules/Settings/LayoutEditor/models/Module.php
> +	public static function getFieldsRelatedWithModule(string $moduleName): array
?

2023-05-18 05:24 UTC, rskrzypczak commented on modules/Vtiger/relations/GetMultiReference.php
> +		$queryGenerator->addCondition($relationField->getName(), $this->relationModel->getParentRecord()->getId(), 'c', false);
?

2023-05-19 09:50 UTC, merged