Fixed getting duplicates in list view
YetiForceCompany/YetiForceCRM pull request #17149
Opened 2023-06-19 12:20 UTC by konadrian

Fixed getting duplicates in list view

2023-06-19 12:22 UTC, ghost commented
## Black Duck Security Report

Merging #17149 into developer will not change security risk.

### Added Components

Clean:       29

### Removed Components

Clean:       26

[Click here to see full report](https://copilot.blackducksoftware.com/github/repos/YetiForceCompany/YetiForceCRM/pull-requests/17149)

2023-06-23 08:16 UTC, rskrzypczak requested changes

2023-06-23 08:16 UTC, rskrzypczak commented on app/QueryGenerator.php
> +			$queryGenerator->setStateCondition($stateFromMainQuery);
The function takes a string as a function argument, and you can also pass an int here, which is an error

2023-08-11 08:54 UTC, rskrzypczak commented on app/QueryGenerator.php
> +            $queryGenerator->setStateCondition($stateFromMainQuery);
```suggestion
            $queryGenerator = new self($this->moduleName, $this->user->getId());
            $queryGenerator->setStateCondition($this->getState());
```

2023-08-11 08:58 UTC, merged